"use client";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/Footer";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";
import { useEffect, useState } from "react";
import { CartContext } from "./_context/CartContext";

const inter = Roboto({ subsets: ["latin"], weight: "900" });

// export const metadata = {
//   title: "E-Commerce Courses",
//   description: "Generated by create next app",
// };
// ----- commented to make "use client"

export default function RootLayout({ children }) {
  let [cart, setCart] = useState([]);
  let [category, setCategory] = useState("all");

  return (
    <ClerkProvider>
      <CartContext.Provider value={{ cart, setCart, category, setCategory }}>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}

/*
to know how clerk visit =>  https://clerk.com/docs/quickstarts/nextjs
*/
