import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";

import { myStore } from "./_RTK/store";
import ReduxProvider from "./_RTK/ReduxProvider";

const roboto = Roboto({ subsets: ["latin"], weight: "900" });

// export const metadata = {
//   title: "E-Commerce Courses",
//   description: "Generated by create next app",
// };
// ----- commented to make "use client"

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      {/* <Provider store={myStore}> */}
      <ReduxProvider>
        {/* I create this component to wrap in the server layout because redux only work in client side */}
        <html lang="en">
          <body className={roboto.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </html>
      </ReduxProvider>
    </ClerkProvider>
  );
}

/*
to know how clerk visit =>  https://clerk.com/docs/quickstarts/nextjs
*/
